### ISSUE TITLE
Creative Assignment 2 Ready for Grading

### ISSUE THREAD

**Issue by maggieweese** [VIS-2129-F2020/maggieweese-vis#2]
Hi Carole and Alex,

My creative assignment 2 is ready for grading! Looking forward to your feedback. The title for the .Rmd is Exercise-2_Maggie-Weese

Thank you!

HTML
https://vis-2129-f2020.github.io/maggieweese-vis/Excercise-2_Maggie-Weese.html

Cheers,
Maggie

**Comment by bauranov** [comment]
Awesome work. I would encourage you to explore additional color palettes. I wish I could give you more feedback, but everything looks great; I have nothing to add. I am looking forward to your next assignment.
