### ISSUE TITLE
Final html and .Rmd for Creative Assignment 3

### ISSUE THREAD

**Issue by maggieweese** [VIS-2129-F2020/maggieweese-vis#3]
Hi Alex and Carole,

I hope you are both having a great day! My html and .Rmd for creative assignment 3 are ready for grading. Looking forward to your feedback.

Please find the html below:
https://vis-2129-f2020.github.io/maggieweese-vis/Creative-Assignment-3_Maggie-Weese.html

All the best,
Maggie

**Comment by bauranov** [comment]
You're making great progress, awesome work!
