### ISSUE TITLE
Creative Assignment 4 Ready for Grading!

### ISSUE THREAD

**Issue by maggieweese** [VIS-2129-F2020/maggieweese-vis#5]
Hi Alex and Carole,

I hope you are both well! My .Rmd and html for creative assignment 4 is ready for grading - looking forward to your feedback. Thank you!

html: 
https://vis-2129-f2020.github.io/maggieweese-vis/Creative-Assignment4_Maggie-Weese_updated.html

All the best,
Maggie

**Comment by bauranov** [comment]
Very creative way to combine assignments 3 and 4. Good work!
